-- ═══════════════════════════════════════════════════════════════════════════
-- FIX: Categories Unique Constraint - Make Slug Tenant-Scoped
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Issue: Categories table has GLOBAL unique constraint on slug
-- - Original migration 20260613000100: "slug text not null unique"
-- - This prevents different tenants from having categories with same slug
-- - Error: "duplicate key value violates unique constraint 'categories_slug_key'"
-- 
-- Solution: 
-- 1. Drop the global unique constraint
-- 2. Create composite unique constraint: (tenant_id, slug)
-- 3. This allows each tenant to have their own "technology", "business", etc.
--
-- Impact:
-- - Category slug must be unique WITHIN tenant, not globally
-- - Each tenant can now have independent category slugs
-- - Multi-tenant isolation is enforced at database level
--
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- Step 1: Drop the old global unique constraint
-- Constraint name "categories_slug_key" was auto-generated by PostgreSQL
ALTER TABLE public.categories 
DROP CONSTRAINT IF EXISTS categories_slug_key;

-- Step 2: Add new composite unique constraint scoped to tenant
-- This ensures (tenant_id, slug) is unique, but same slug can exist in different tenants
ALTER TABLE public.categories
ADD CONSTRAINT categories_tenant_slug_unique UNIQUE (tenant_id, slug);

-- Step 3: Drop and recreate the (tenant_id, slug) index to ensure it's optimized
DROP INDEX IF EXISTS idx_categories_slug;
CREATE INDEX IF NOT EXISTS idx_categories_tenant_slug 
ON public.categories(tenant_id, slug)
WHERE deleted_at IS NULL;

COMMIT;
