-- ═══════════════════════════════════════════════════════════════════════════
-- FIX: GOOGLE DRIVE DISCONNECT PERMISSION ERROR
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- Issue:
-- - Tenant admins could not disconnect Google Drive
-- - Error: "Forbidden: Requires manage_settings permission"
-- - Root cause: has_permission('manage_settings') checks GLOBAL roles only
-- - Tenant admins only have roles in tenant_memberships (not global roles)
--
-- Solution:
-- - Edge Function (google-drive-disconnect) now validates tenant-scoped admin role
-- - Checks if user is 'admin' or 'owner' in tenant_memberships for the specific tenant
-- - No longer depends on has_permission() which only checks global roles
-- - RLS policy remains unchanged (allows super_admin or those with manage_settings)
-- - Edge Function is FIRST security layer before RLS
--
-- Security Implications:
-- - Tenant owners/admins can now manage their Google Drive connection
-- - Only admins and owners (verified via tenant_memberships) can disconnect
-- - Super admins can always manage any tenant's connections
-- - No change to RLS - database-level security still enforced
-- - No change to Google OAuth Client ID or redirect URIs
--
-- ═══════════════════════════════════════════════════════════════════════════

begin;

-- No database schema changes needed
-- The fix is entirely in the Edge Function logic:
-- supabase/functions/google-drive-disconnect/index.ts
-- 
-- OLD LOGIC:
--   1. Validate tenant membership (member exists in tenant_memberships)
--   2. Check has_permission('manage_settings') - FAILS for tenant admins
--   3. Update database
--
-- NEW LOGIC:
--   1. Validate tenant membership AND check role (admin/owner) in tenant_memberships
--   2. No global permission check
--   3. Update database
--
-- The database RLS policy is NOT changed:
-- - It still checks has_permission('manage_settings') OR is_super_admin()
-- - This is acceptable because:
--   a) Edge Function is the PRIMARY security check (tenant-scoped)
--   b) RLS policy is the SECONDARY security check (global)
--   c) Tenant admins will pass the Edge Function check
--   d) When they update the database, RLS may still reject based on global role
--   e) BUT: The update is called with service_role key (not user key)
--   f) So RLS doesn't actually block the update in this context
--
-- Future improvement: Update RLS policy to also check tenant-scoped roles
--
-- Test:
-- 1. Login as tenant admin
-- 2. Go to /admin/media
-- 3. Click "Disconnect Google Drive"
-- 4. Should succeed (no 403 error)

-- This migration is DOCUMENTATION ONLY
-- The actual fix is in the Edge Function source code

commit;
