-- ═══════════════════════════════════════════════════════════════════════════
-- FIX: Categories Unique Constraint - Make Slug Tenant-Scoped
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Issue: Categories table has GLOBAL unique constraint on slug
-- - Original migration 20260613000100: "slug text not null unique"
-- - This prevents different tenants from having categories with same slug
-- - Error: "duplicate key value violates unique constraint 'categories_slug_key'"
-- 
-- Solution: 
-- 1. Drop the global unique constraint
-- 2. Create composite unique constraint: (tenant_id, slug)
-- 3. This allows each tenant to have their own "technology", "business", etc.
--
-- Impact:
-- - Category slug must be unique WITHIN tenant, not globally
-- - Each tenant can now have independent category slugs
-- - Multi-tenant isolation is enforced at database level
--
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- Step 1: Drop the old global unique constraint
-- Constraint name "categories_slug_key" was auto-generated by PostgreSQL
ALTER TABLE public.categories 
DROP CONSTRAINT IF EXISTS categories_slug_key;

-- Step 2: Add new composite unique constraint scoped to tenant
-- CRITICAL: Use a partial unique index that excludes soft-deleted rows (deleted_at IS NULL)
-- This allows deleted categories to be recreated with the same slug
-- PostgreSQL doesn't support WHERE clause in UNIQUE constraints, so we use a unique index instead

-- Step 3: Create a unique index instead (allows partial uniqueness)
-- This ensures (tenant_id, slug) is unique ONLY for non-deleted rows
-- Allows same slug to exist in different tenants and allows slug reuse after soft delete
DROP INDEX IF EXISTS categories_slug_key;
DROP INDEX IF EXISTS idx_categories_slug;
DROP INDEX IF EXISTS idx_categories_tenant_slug;

CREATE UNIQUE INDEX categories_tenant_slug_unique 
ON public.categories(tenant_id, slug)
WHERE deleted_at IS NULL;

-- Step 4: Create regular index for query performance
CREATE INDEX IF NOT EXISTS idx_categories_tenant_slug_all 
ON public.categories(tenant_id, slug);

COMMIT;
